---
title: 'Data Camp Chapter 1: Unsupervised Learning Notes'
author: "Corey Pang"
date: "6/28/2017"
output: html_document
---

### _Unsupervised Learning_
+ Finding patterns in data without making predictions
+ Finding structure in unlabeled data

#### _Goals_
+ Find homogeneous subgroups within a population, called clustering
+ Segmenting a market of consumers
+ Finding movies most like another movie
+ Finding patterns in the features of the data
  
### _Dimensionality Reduction_

#### _Goal_
+ Visually represent high D data while maintaining much of the data variability
+ Pre-processing step for supervised learning
+ Generally no goal of the analysis

### _Supervised Learning_
+ Making predictions based on labeled data
+ Predictions like regression or classification

> __Question: + Labeled vs Unlabeled?__

#### _K-means clustering algorithm_
* Used to find homogeneous subgroups within a population
* Breaks observations into a predefined number of subgroups 
* In R: kmeans(x, centers =  , nstart = )
    + x: the data, one observation per row, one feature per column
    + centers: # of predetermined groups/clusters
    + nstart: run the algorithm this number of times 
* ‘summary(km.out)’
* print(km.out) and you can specify using $
* For plotting the data, you can specify the color with the argument ‘col = km.out$cluster)
* kmeans randomly initializes the center of the clusters and then assigns the observations to the closest center. This must be repeated many times until the observations no longer change assignments 
    + Sum of squares can be calculated from the distance between the observation and the center of the cluster, we want to minimize this, which is what kmeans() does 

#### __Selecting the number of clusters when it is not specified__
* Will need to run the algorithm many times with different values for ‘centers’ using a for loop and then plotting the total within sum of squares 
* Look for where the ‘elbow’ occurs, this may not be obvious so it is up to you to choose where you think the ‘elbow’ occurs






