---
title: "PCA on Point Level Data"
author: "Corey Pang"
date: "7/2/2017"
output: html_document
---

```{r setup, include=FALSE}
install.packages("devtools", repos = "http://cran.us.r-project.org")
library(devtools)
install_github("vqv/ggbiplot", force=TRUE)
library(ggbiplot)
install.packages("FactoMineR", repos = "http://cran.us.r-project.org")
library(FactoMineR)
getwd()
dir <- file.path(getwd(),"Point level data")
out <- read.csv(file.path(dir, "MU-BU-Ghana.csv"))
newout <- na.omit(out)
water <- newout[,57:80]
lulc.var <- newout[,29:56]
lulc.wet.var <- cbind(newout[,19:26], newout[, 29:56])
```
 
### PCA on Water Variables 
```{r1}
pr.data <- prcomp( water, scale = TRUE, center = TRUE)
summary(pr.data) 
pr.water.var <- pr.data$sdev^2
pve.water <- pr.water.var/sum(pr.water.var)
percent.pve.water <- pr.water.var/sum(pr.water.var) * 100
```
```{r1a}
barplot(percent.pve.water, xlab="PC",
            ylab="Percent Variance", 
            main = "Barplot of Percentage of Total Variation",
            names.arg=1:length(percent.pve.water), las=1, 
            ylim=c(0,max(percent.pve.water)), col="gray")
            abline(h=1/ncol(water)*100, col="red")
```
The red line on the bar plot indicates the amount of variance each variable would contribute if all contributed the same amount. As we can see from the plot, 7 principal components explain more than one variable’s worth of information. 

```{r1b}
percent.pve.water[1:7]
sum(percent.pve.water[1:7])
```

These 7 principal components account for 79.2% of the variability. 

```{r1c}
water.loadings <- pr.data$rotation[,1:7]
sqrt(1/ncol(water))	# cutoff for "important" loadings
print(water.loadings, digits = 1, cutoff = sqrt(1/ncol(water)), sort = TRUE)
plot(pr.data$x, col = newout$Total_MU_Present__VNTR_)
?plot
```

```{r1d}
scores <- pr.data$x
#biplot(scores[,1:7], loadings[,1:7], cex=0.7, )
ggbiplot(pr.data, obs.scale = 1, var.scale = 1,
              ellipse = TRUE, 
              circle = TRUE,
              groups = newout$ENDEM_DIST)
ggbiplot(pr.data, obs.scale = 1, var.scale = 1,
              ellipse = TRUE, 
              circle = TRUE,
              groups = newout$Total_MU_Present__VNTR_)
pr.data <- PCA( newout[,57:80], scale.unit = TRUE, ncp = 6, graph = FALSE)
dimdesc(pr.data, axes = 1:6)
```
Looking at the dimdesc table, Calcium, Calcium Hardness, and total dissolved solids are the highest correlated variables with principle component 1, which explains 31.3% of the variation. If we look at principal component 2, total Nitrogen, Nitrate, and Nitrogen/Phosphate ratio are the highest positively correlated variables, which explains 12.6% of the total variation in the data. Looking at principal component 3, which explains almost 10% of the total variation, dissolved oxygen percent saturation is moderately negatively correlated, while Field turbidity (NTU) and color apparent are moderately positively associated with it. We can look at this for all the different 6 components we selected. 

### Principal Components Breakdown 
```{r1e}
loadings <- data.frame(ID = rownames(pr.data$rotation), pr.data$rotation[,1:6], stringsAsFactors=F)
loadings.m <- melt(loadings, id="ID", 
                   measure=c("PC1", "PC2", 
                             "PC3", "PC4", "PC5", "PC6"), 
                   variable.name="Factor", value.name="Loading")
ggplot(loadings.m, aes(x = ID, y = Loading)) + 
  facet_wrap(~ Factor, nrow = 1) +
  geom_bar(stat="identity") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  ggtitle('PCA on Water Variables from Point Level Data Data')
```


### PCA on LULC Variables without Wetness Index Variables

```{r2}
pr.lulc.data <- prcomp(x = lulc.var, scale = TRUE, center = TRUE)
summary(pr.lulc.data) 
pr.var <- pr.lulc.data$sdev^2
pve <- pr.var/sum(pr.var)
percent.pve <- pr.var/sum(pr.var) * 100
barplot(percent.pve, xlab="PC", 
            ylab="Percent Variance", 
            main = "Barplot of Percentage of Total Variation",
            names.arg=1:length(percent.pve), las=1, 
            ylim=c(0,max(percent.pve)), col="gray")
            abline(h=1/ncol(water)*100, col="red")
```

```{r2a}
ggbiplot(pr.lulc.data, obs.scale = 1, var.scale = 1,
              ellipse = TRUE, 
              circle = TRUE,
              groups = newout$Total_MU_Present__VNTR_)
ggbiplot(pr.lulc.data, obs.scale = 1, var.scale = 1,
              ellipse = TRUE, 
              circle = TRUE,
              groups = newout$ENDEM_DIST)
pr.data <- PCA(lulc.var, scale.unit = TRUE, ncp = 6, graph = FALSE)
dimdesc(pr.data, axes = 1:6)
```
Principal component 1 accounts for 30.1% of the variation and is highly positively associated with the Shrubland variable at all levels. PC1 is highly negatively associated with Forest at all levels. Principal component 2 is pretty highly positively associated with the Wetlands variable at all levels and is somewhat negatively associated with the Cropland variables at all levels. PC2 accounts for 16.5% of the variability in the data. Principal component 3 is somewhat positively associated with Forest at all levels and has a moderate to strong negative association with Urban variables at all levels. The rest of the correlations are displayed above. 

### Principal Components Visual Breakdown

```{r2b}
loadings <- data.frame(ID = rownames(pr.lulc.data$rotation), pr.lulc.data$rotation[,1:6], stringsAsFactors=F)
loadings.m <- melt(loadings, id="ID", 
                   measure=c("PC1", "PC2", 
                             "PC3", "PC4", "PC5", "PC6"), 
                   variable.name="Factor", value.name="Loading")
ggplot(loadings.m, aes(x = ID, y = Loading)) + 
  facet_wrap(~ Factor, nrow = 1) +
  geom_bar(stat="identity") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  ggtitle('PCA on LULC Variables from Point Level Data Data')
```
### PCA on LULC Variables with Wetness Index Variables
```{r3}
pr.lulc.wet.data <- prcomp(x = lulc.wet.var, scale = TRUE, center = TRUE)
summary(pr.lulc.wet.data) 
pr.var <- pr.lulc.wet.data$sdev^2
pve <- pr.var/sum(pr.var)
percent.pve <- pr.var/sum(pr.var) * 100
barplot(percent.pve, xlab="PC",
            ylab= "Percent Variance", 
            main = "Barplot of Percentage of Total Variation",
            names.arg=1:length(percent.pve), las=1, 
            ylim=c(0,max(percent.pve)), col="gray")
            abline(h=1/ncol(water)*100, col="red")
```
```{r3a}
ggbiplot(pr.lulc.wet.data, obs.scale = 1, var.scale = 1,
              ellipse = TRUE, 
              circle = TRUE,
              groups = newout$Total_MU_Present__VNTR_)
ggbiplot(pr.lulc.wet.data, obs.scale = 1, var.scale = 1,
              ellipse = TRUE, 
              circle = TRUE,
              groups = newout$ENDEM_DIST)
pr.data <- PCA(lulc.wet.var, scale.unit = TRUE, ncp = 6, graph = FALSE)
dimdesc(pr.data, axes = 1:6)
```
We see a difference with the addition of the wetness index variables. Now, principal component 1, is highly positively associated with the Wetness Index buffer Average at the 1KM and 5KM levels. It is also moderately positively associated with the Shrubland at all levels. It is also moderately negatively associated with Forest at all levels. Much like the analysis above, the second principal component is highly positively associated with the Wetlands variables at all levels and negatively associated with Cropland. The same thing with principal component 3. 
### PCA Breakdown of Components

```{r3b}
loadings <- data.frame(ID = rownames(pr.data$rotation), pr.data$rotation[,1:6], stringsAsFactors=F)
loadings.m <- melt(loadings, id="ID", 
                   measure=c("PC1", "PC2", 
                             "PC3", "PC4", "PC5", "PC6"), 
                   variable.name="Factor", value.name="Loading")
ggplot(loadings.m, aes(x = ID, y = Loading)) + 
  facet_wrap(~ Factor, nrow = 1) +
  geom_bar(stat="identity") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  ggtitle('PCA on Water Variables from Point Level Data Data')
```
----------------------------------------------------------------------
#### k-means algorithm for Water Variables

```{r4}
# Initialize total within sum of squares error: wss
wss <- 0
water <- newout[,57:80]
# For 1 to 15 cluster centers
for (i in 1:15) {
  km.out <- kmeans(water, centers = i, nstart = 20)
  # Save total within sum of squares to wss variable
  wss[i] <- km.out$tot.withinss
}

# Plot total within sum of squares vs. number of clusters
plot(1:15, wss, type = "b", 
     xlab = "Number of Clusters", 
     ylab = "Within groups sum of squares")
```
There is no clear "elbow" here, I would choose 5 clusters but it is not clear what number is optimal. 

```{r5}
km.water.out <- kmeans(x = water, centers = 5, nstart = 20)
summary(km.water.out)
print(km.water.out$cluster)
```
What should we plot here?

#### k-means algorithm for LULC Variables without Wetness Index Variables

```{r6}
# Initialize total within sum of squares error: wss
wss <- 0
# For 1 to 15 cluster centers
for (i in 1:15) {
  km.out <- kmeans(lulc.var, centers = i, nstart = 20)
  # Save total within sum of squares to wss variable
  wss[i] <- km.out$tot.withinss
}

# Plot total within sum of squares vs. number of clusters
plot(1:15, wss, type = "b", 
     xlab = "Number of Clusters", 
     ylab = "Within groups sum of squares")
```
For this plot, there is a little bit more of a clear elbow at either 3 or 4 clusters. I will proceed with 3 clusters.  

```{r7}
km.lulc.out <- kmeans(x = lulc.var, centers = 3, nstart = 20)
summary(km.lulc.out)
print(km.lulc.out$cluster)
```
What should we plot here?

#### k-means algorithm for LULC Variables with Wetness Index Variables

```{r8}
# Initialize total within sum of squares error: wss
wss <- 0
# For 1 to 15 cluster centers
for (i in 1:15) {
  km.lulc.wet.out <- kmeans(lulc.wet.var, centers = i, nstart = 20)
  # Save total within sum of squares to wss variable
  wss[i] <- km.out$tot.withinss
}

# Plot total within sum of squares vs. number of clusters
plot(1:15, wss, type = "b", 
     xlab = "Number of Clusters", 
     ylab = "Within groups sum of squares")
```
For this plot, there is a little bit more of a clear elbow at either 3 or 4 clusters. I will proceed with 3 clusters. This is basically the exact same plot as the LULC without including the Wetness Index variables.

```{r9}
km.lulc.wet.out <- kmeans(x = lulc.wet.var, centers = 3, nstart = 20)
summary(km.lulc.wet.out)
print(km.lulc.wet.out$cluster)
```

#### Hierarchical Clustering for Water Variables
```{r10}
hclust.complete <- hclust(dist(water), method = 'complete')
plot(hclust.complete, main = 'Complete')
```