---
title: "Pileggi PLOS ONE 2017 Notes"
author: "Corey Pang"
output: html_document
---

+ _Buruli Ulcer_ is a neglected tropical disease caused my infection with _mycobacterium ulcerans_.
+ The best treatment for BU is early detection rather than preventative methods.
+ The mode of transmission has not been conclusively identified.
+ Some hypothesized modes of transmission are:
    1. Mosquitoes or aquatic insects as a vector
    2. Aerosol Transmission
    3. Contact through open skin lesion
+ Mycobacterium Ulcerans is the causative agent of BU  
+ Positive associations with BU incidence were found with mean arsenic content of soil, proximity to gold mining sites, irrigated rice crops area, agriculture,forest, potential maximum soil water retention, and wetness index variability.
+ Negative Associations with BU were found with dam surface area, urban land cover, and mean elevation.

##### Purpose of this Study
+ Investigate the spatial distribution of M. ulcerans among aquatic sites in Ghana and identify environmental characteristics associated with the presence of M. ulcerans.
+ _Hypothesis_ the presence of M. ulcerans was associated with bothbroad scale environmental features as well as highly localized characteristics of aquatic systems.

##### Study Area
+ Chose 3 areas in Ghana
    1. Ashanti, highly endemic region (majority of districts report cases of BU)
    2. Greater Accra, mixed endemic region (some districts report cases of BU)
    3. Volta, non-endemic region (no districts report cases of BU)
  
+ District level reporting is defined based on whether the sampled community is located within a district that reported BU cases in the same years.
+ Community level reporting is defined as the presence of reported BU cases in the sampled communities.

#### Statistical Analysis
+ Logistic regression was used to identify variables associated with the presence of M. ulcerans among the aquatic sites.
+ Explored the association between reported BU cases and M. ulcerans presence.

#### Results 
+ Kulldorff's spatial scan statistic found no significant spatial clusters of M. ulcerans positive aquatic sites.There was no significant groupings of the M. Ulcerans positive aquatic sites.
+ Logistic regression was used to identify the factors associated with M. Ulcerans 
+ The 7 Main Effects were: 
    1. Region
    2. Elevation
    3. Wetness Index at the Site
    4. Standard deviation of wetness index within 500 m of the site
    5. Indicator for urban land cover within 100 m of the site
    6. Indicator for forest land cover within 1 km of the site
    7. Log of calcium water hardness
+ This model also contained three interaction terms with region: elevation, standard
deviation of wetness index within 500m of the site, and calcium water hardness.
+ The odds of M. ulcerans presence increased as elevation increased
+ As the wetness index at the site increased, the odds of M. ulcerans presence decreased
+ As the standard deviation of the wetness index within 500m of the site increased, the odds of M. ulcerans decreased in Accra but increased in Ashanti.
+ Sites that had urban land cover present within 100 m but did not exhibit forest within 1 km had the highest odds of M. ulcerans presence, then urban/forested, and then non-urban/non-forested, and lastly non-urban/forested areas had the lowest odds of M. ulcerans presence.
+ M. ulcerans presence was weakly negatively associated with water calcium hardness in Accra and strongly positively associated with calcium water hardness in Ashanti.
+ For both Accra and Ashanti, the presence of M. ulcerans had a negative association with dissolved oxygen percent saturation and a positive association with log of nitrate.
+ Land cover representing most disturbed areas are associated with a higher probability of M. ulcerans presence compared to land cover representing less disturbed areas.

#### Question: 
It says that BU is now present in the Volta region? Has the been explored to look for differences between when there were no reported cases to now when there are reported cases?

###### __Water Variables__
* The best fitting model relating the presence of M. ulcerans to physical and chemical properties of water contains dissolved oxygen percent saturation, nitrate, and calcium water hardness.
* Buruli Ulcer has been associated with both moving and still waters.

###### __Land Use/Land Cover Variables__
* Chose to consider indicators for the presence of specific LULC categories within a buffer in
addition to the percentage observed for two reasons:
    1. The percent LULC may not have a linear relationship with the log odds of M. ulcerans presence and the true relationship may be difficult to ascertain
    2. Provide a more robust measure than class percentages, reducing the potential impact of unusual observations
* Sites with more disturbed environments (urbanized, non-forested) were more likely to have M. ulcerans present compared to less disturbed environments (forested, non-urbanized).
    * __Deforestation__ reduces riparian cover which may lead to an increase in temperature in the aquatic systems to a degree necessary for M. Ulcerans can grow.
    * __Urbanization__ can result in increased sedimentation in aquatic systems, attenuating UV penetration, and facilitating favorable conditions for M. ulcerans growth
    
###### __Terrain Variables__
* Elevation, Wetness Index at the site, and variability of Wetness Index in the viscinity of the site were found to be associated with MU 
    * Negative association between the presence of M. Ulcerans and wetness index at the site 
    * Positive Association between the presence of M. Ulcerans and elevation 
* Areas of high wetness index or low elevation areas may be more prone to flooding or fast moving water that could wash out the natural site for M. ulcerans.


