---
title: 'DC: Writing Functions'
author: "Corey Pang"
date: "7/11/2017"
output: html_document
---

### Functions
    * There are 3 parts to a function
        1. Arguments
        2. Body
        3. Environment
    
* Scoping is the process R uses to look up values
* If the name is not defined locally then it looks one environment up, if nothing is defined it will return an error

* There are two types of vectors in R
    1. Atomic
    2. Lists 
    * Every vector has 2 key properties
        1. lengthof(x)
        2. typeof(x)
        
#### When to write a function?
* Once you've copied and pasted twice, it's time to write a function

#### What makes a good function?
* Correct
* Understandable for humans
    * Use good names 
    __Naming Styles__
    * Pick a consistent style for long names
    * Don't name functions already existing in R
    * Should be verbs for functions
    * For arguments, use nouns
    * Argument Orders:
        * Data arguments come first 
        * Detail arguments should always be given defauly values 
        
### Examples
mean_ci <- function(x, level = 0.95) {
  if (length(x) == 0) {
    return(c(-Inf, Inf)) 
  }
  se <- sd(x) / sqrt(length(x))
  alpha <- 1 - level
  mean(x) + se * qnorm(c(alpha / 2, 1 - alpha / 2))
}

--------------------------------------------------------

col_sd <- function(df) {
  output <- numeric(length(df))
  for (i in seq_along(df)) {
    output[[i]] <- sd(df[[i]])
  }
  output
}

--------------------------------------------------------

#### Passing Functions as Arguments
* prrr package
    * map_dbl,chr,...(.x, .f, ...)
1. The map function loops over a vector .x
2. Doing .f to each element
3. Returns the Results 

Advantages:
1. Handy shortcuts for calling .f
2. More consistent than lapply() and sapply()
3. Takes much less time to solve iteration Problems

##### Load the purrr package
* library(purrr)
##### Use map_dbl() to find column means
* map_dbl(df, mean)
##### Find the mean of each column, excluding missing values
* map_dbl(planes, mean, na.rm=TRUE)
##### Find the 5th percentile of each column, excluding missing values
* map_dbl(planes, quantile, probs = 0.05, na.rm=TRUE)

The pipe operator: 
* %>%
* x %>% y means f(x,y)
* we can chain together many operations using the pipe

Adverbs:
* safely(): captures the successful result or the error, always returns a list
* possibly(): always succeeds, you give it a default value to return when there is an error
* quietly(): captures printed output, messages, and warnings instead of capturing errors

#### Using map2
* use map2() to iterate over two arguments
* use pmap() to iterate over many arguments 
    * pmap(.l, .f, ...)
* invoke_map() to iterate over functions
    * invoke_map(.f, .x = list(NULL, ...))

